const regionCache=new WeakMap();
const boundsCache=new WeakMap();
function overlaps(a,b,pad){return !(a.x+a.w+pad<b.x||b.x+b.w+pad<a.x||a.y+a.h+pad<b.y||b.y+b.h+pad<a.y)}
function mergeClose(boxes,pad){let out=boxes.map(b=>({...b})),changed=true;while(changed){changed=false;outer:for(let i=0;i<out.length;i++){for(let j=i+1;j<out.length;j++){if(!overlaps(out[i],out[j],pad))continue;const a=out[i],b=out[j],x=Math.min(a.x,b.x),y=Math.min(a.y,b.y),r=Math.max(a.x+a.w,b.x+b.w),bot=Math.max(a.y+a.h,b.y+b.h);out[i]={x,y,w:r-x,h:bot-y};out.splice(j,1);changed=true;break outer}}}return out}
export function getAlphaBounds(image){if(!image?.complete||!image.naturalWidth)return null;if(boundsCache.has(image))return boundsCache.get(image);const scale=4,w=Math.ceil(image.naturalWidth/scale),h=Math.ceil(image.naturalHeight/scale),canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(image,0,0,w,h);const data=ctx.getImageData(0,0,w,h).data;let minX=w,minY=h,maxX=-1,maxY=-1;for(let y=0;y<h;y++)for(let x=0;x<w;x++){if(data[(y*w+x)*4+3]<10)continue;if(x<minX)minX=x;if(x>maxX)maxX=x;if(y<minY)minY=y;if(y>maxY)maxY=y}if(maxX<0)return null;const pad=8,sx=Math.max(0,minX*scale-pad),sy=Math.max(0,minY*scale-pad),ex=Math.min(image.naturalWidth,(maxX+1)*scale+pad),ey=Math.min(image.naturalHeight,(maxY+1)*scale+pad),b={x:sx,y:sy,w:Math.max(1,ex-sx),h:Math.max(1,ey-sy)};boundsCache.set(image,b);return b}
export function getSpriteRegions(image){if(!image?.complete||!image.naturalWidth)return[];if(regionCache.has(image))return regionCache.get(image);const scale=4,w=Math.ceil(image.naturalWidth/scale),h=Math.ceil(image.naturalHeight/scale),canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(image,0,0,w,h);const data=ctx.getImageData(0,0,w,h).data,seen=new Uint8Array(w*h),boxes=[];for(let y=0;y<h;y++)for(let x=0;x<w;x++){const p=y*w+x;if(seen[p]||data[p*4+3]<10)continue;let minX=x,maxX=x,minY=y,maxY=y;const q=[p];seen[p]=1;for(let qi=0;qi<q.length;qi++){const cur=q[qi],cx=cur%w,cy=(cur/w)|0;for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const nx=cx+dx,ny=cy+dy;if(nx<0||ny<0||nx>=w||ny>=h)continue;const np=ny*w+nx;if(seen[np]||data[np*4+3]<10)continue;seen[np]=1;q.push(np);if(nx<minX)minX=nx;if(nx>maxX)maxX=nx;if(ny<minY)minY=ny;if(ny>maxY)maxY=ny}}const bw=(maxX-minX+1)*scale,bh=(maxY-minY+1)*scale;if(bw>=32&&bh>=32&&bw*bh>=1200)boxes.push({x:minX*scale,y:minY*scale,w:bw,h:bh})}boxes=mergeClose(boxes,10);boxes=mergeClose(boxes,18);boxes.sort((a,b)=>{const tol=Math.max(30,Math.min(a.h,b.h)*.25),ay=a.y+a.h/2,by=b.y+b.h/2;if(Math.abs(ay-by)<=tol)return a.x-b.x;return a.y-b.y});const result=boxes.map(b=>({x:Math.max(0,b.x-4),y:Math.max(0,b.y-4),w:Math.min(image.naturalWidth-b.x+4,b.w+8),h:Math.min(image.naturalHeight-b.y+4,b.h+8)}));regionCache.set(image,result);return result}
export function drawSpriteRegion(ctx,image,region,target){if(!image?.complete||!image.naturalWidth||!region)return false;const pad=2,sx=Math.max(0,region.x-pad),sy=Math.max(0,region.y-pad),sw=Math.min(image.naturalWidth-sx,region.w+pad*2),sh=Math.min(image.naturalHeight-sy,region.h+pad*2),scale=Math.min(target.w/sw,target.h/sh),dw=Math.max(1,Math.round(sw*scale)),dh=Math.max(1,Math.round(sh*scale));ctx.drawImage(image,sx,sy,sw,sh,Math.round(-dw/2),Math.round(-dh/2),dw,dh);return true}
export function drawSourceSprite(ctx,image,source,target,rotation=0,flipX=false){if(!image?.complete||!image.naturalWidth||!source)return false;const {x,y,w,h}=source,scale=Math.min(target.w/w,target.h/h),dw=Math.max(1,Math.round(w*scale)),dh=Math.max(1,Math.round(h*scale));ctx.save();if(rotation)ctx.rotate(rotation);if(flipX)ctx.scale(-1,1);ctx.drawImage(image,x,y,w,h,Math.round(-dw/2),Math.round(-dh/2),dw,dh);ctx.restore();return true}
export function drawGridSprite(ctx,image,index,cols,rows,target){if(!image?.complete||!image.naturalWidth||!cols||!rows)return false;const cw=image.naturalWidth/cols,ch=image.naturalHeight/rows,c=index%(cols*rows),sx=(c%cols)*cw,sy=Math.floor(c/cols)*ch,scale=Math.min(target.w/cw,target.h/ch),dw=Math.max(1,Math.round(cw*scale)),dh=Math.max(1,Math.round(ch*scale));ctx.drawImage(image,sx,sy,cw,ch,Math.round(-dw/2),Math.round(-dh/2),dw,dh);return true}
export function drawIndexedSprite(ctx,image,index,target){const regions=getSpriteRegions(image);return drawSpriteRegion(ctx,image,regions[index],target)}
